import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="bg-gray-800 fixed w-full">
					<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
						<div className="flex items-center justify-between h-16">
							<div className="flex-shrink-0">
								<a href="#" className="text-white font-bold text-xl">Supabase</a>
							</div>
							<div className="hidden md:block">
								<div className="ml-10 flex items-baseline space-x-4">
									<Link className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" href="/auth">Auth</Link>
									<Link className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" href="/">Home</Link>
									<Link className="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" href="/todo">CRUD</Link>
								</div>
							</div>
						</div>
					</div>
				</nav>
				<div className="flex flex-col">
				</div>
				{children}
				<Toaster />
			</body>
		</html>
	);
}
